name: "Add labels to github issues based on context"
on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  shared-issues:
    name: "Add Labels to Issues.  Safe to Merge on fail"
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue Command from workflow-actions
        uses: nick-fields/private-action-loader@6fa713597d3de3707f8b7a3029a5c262f32c5bca # v3.0.12
        with:
          pal-repo-token: "${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}"
          pal-repo-name: airbytehq/workflow-actions@production
          # the following input gets passed to the private
          token: "${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}"
          # ref: https://github.com/airbytehq/workflow-actions/blob/main/src/bin_issue.ts
          command: "issue"
