name: Trigger action in cloud based on push
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  repo-sync:
    name: "Fire a Repo Dispatch event to airbyte-cloud"
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2.1.2
        with:
          token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
          repository: airbytehq/airbyte-cloud
          event-type: oss-push-to-master
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
